language: ruby

sudo: false

env:
  global:
    - LANG=en_US.UTF-8
    - LANGUAGE=en_US.UTF-8
    - LC_ALL=en_US.UTF-8

matrix:
  include:
    - env: OSX=10.10 HOMEBREW_RUBY=2.0.0
      os: osx
      osx_image: xcode7.1
      rvm: system

branches:
  only:
    - master

cache:
  edge: true
  directories:
    - $HOME/.gem

before_install:
  - . ci/travis/before_install.sh

install:
  - . ci/travis/install.sh

before_script:
  - . ci/travis/before_script.sh

script:
  - . ci/travis/script.sh


notifications:
  email: false
